#!/bin/sh
# Shell script which wraps the docker command

if  [ $DOCKER_MACHINE_NAME ]
then
  export USER_ID=1000
else
  export USER_ID=`id -u $USER`
fi

LINKS=""
for LINK_NAME in $(docker ps --format "{{.Names}}")
do
  LINKS=$LINKS"--link $LINK_NAME:$LINK_NAME "
done

docker run --rm -it \
  -v ide-history:/home/history \
  -v nvm-aliases:/nvm/alias \
  -v nvm-versions:/nvm/versions \
  -v yarn-cache:/usr/local/share/.cache/yarn/ \
  -v "$HOME/.ssh":/home/.ssh -v "$PWD":/workdir/ \
  -e USER_ID=$USER_ID \
  -P \
  cmc333333/ide:typescript $@
