#!/bin/sh
# Shell script which wraps the docker command

USER_ID=$(id -u $USER)
DIR_HASH=$(echo $PWD | md5sum | cut -d ' ' -f1)

docker ps -a | grep $DIR_HASH > /dev/null
if [ $? -ne 0 ]; then
  docker create \
    --volume ide-cache:/var/cache/ide \
    --volume "$HOME/.ssh":/home/.ssh \
    --volume "$PWD":/usr/src/workspace/ \
    --name ide-$DIR_HASH \
    cmc333333/ide:unified \
    sleep 365d > /dev/null
fi

docker start ide-$DIR_HASH > /dev/null

docker exec \
  --env USER_ID=$USER_ID \
  --interactive \
  --tty \
  ide-$DIR_HASH \
  entrypoint.sh $@

docker kill ide-$DIR_HASH > /dev/null
